GET http://127.0.0.1:3030/hello/there HTTP/2.0

###
 
GET http://127.0.0.1:3030/hello/world HTTP/2.0

###
GET http://127.0.0.1:3030/hello2/there HTTP/2.0

###
 
GET http://127.0.0.1:3030/hello2/world HTTP/2.0

###
 
GET http://127.0.0.1:3030/health HTTP/2.0
